### ISSUE TITLE
View Source Block not working

### ISSUE THREAD

**Issue by lpfann** [timothycrosley/portray#40]
On my generated docs the "View Source" Block is not working.
The button is not visible and the source code is displayed without formatting etc.

As you can see here: https://fri.lpfann.me/reference/fri/parameter_searcher/

I used version 1.3.

**Comment by timothycrosley** [comment]
Hi @lpfann,

After a quick investigation I believe the issue is caused by a missing markdown extension, and I've made a pull request against your project to add that extension. 

Thanks!

~Timothy

**Comment by lpfann** [comment]
Thank you for your PR!

**Comment by timothycrosley** [comment]
Happy to help! :)

**Comment by PanRe** [comment]
Hey Timothy,

I actually ran into the same problem. I needed the pymdownx.arithmatex extension (for Latex rendering) and i defined this in the toml file. However, i was not aware that i am over writing a "needed" extensions list. There was nothing like that mentioned in the docs ;)

Since the chances are high that much more people run into this issue (i guess a lot of people like Latex) i would vote for a renaming of this extension list to avoid this overwriting issue and thus to save your magic setup! If you would name the current extension list smth like base_extensions (to give people a hint that those are needed by you) and a second new one called additional_extensions (for people like me), you could rely on your needed extionsions. I hope you get my idea :)

Kind regards,
Reini

**Comment by timothycrosley** [comment]
@PanRe I really like your suggestion here! I've done a slight variation of it in the latest release, exposing an `extra_markdown_extensions` config option, that will always be additive against portray's defaults: https://timothycrosley.github.io/portray/docs/quick_start/4.-configuration/.

I chose this approach simply because it would maintain backward compatibility with existing portray users.

Hope this is helpful!

~Timothy

**Comment by PanRe** [comment]
Thanks a lot! True, i was not thinking of backward compatibility... Anyway thanks for implementing!

~ Reini
